### PR TITLE
add new module ProcessTarball instead of import_tarball

### PR DESCRIPTION
**Pull request by andreeap**
@oalders I can't reopen the last pull request, I did a new one to see if tests are failing for what I have changed

### CODE REVIEW

**Comment by oalders** [comment]
@andreeap where is the test file you added?

**Comment by andreeap** [comment]
I have not included that yet, it is included on my forked repository,
because the way I changed the files should still be passing the tests, but
I think I was wrong.

**Comment by oalders** [comment]
If you don't include it, we can't help you with it.

**Comment by andreeap** [comment]
I added the test file on this branch too, but like I said on hackpad, I am not sure where to include this test. The logic in the test is  that I added an archive to fakecpan, and then verified how many files got indexed and compared to how many should have been.

**Comment by oalders** [comment]
What do you mean by "where to include"?

**Comment by andreeap** [comment]
I added this to t//script/release and I am not sure if it's ok. Do I have to do something else to be sure it will get into the test?

**Comment by oalders** [comment]
When Travis runs, it will run anything under t/ that has a ".t" suffix, so this is fine.  As far as naming the test, we can look at that later.  The main thing is that it can be run.

**Comment by andreeap** [comment]
I made a mistake when I named it, I can push the change, but I will let travis do its job first.

**Comment by andreeap** [comment]
I have not closed this, is there something that closes pull requests automatically?

**Pull request closed without merging**
