### PR TITLE
[WIP] Elasticsearch upgrade

### PR DESCRIPTION
**Pull request by oalders**
Making a PR so that review is a touch easier.  Nicht mergen!

To use this branch you can do something like:
```
cd metacpan-api
git clone git@github.com:CPAN-API/p5-elasticsearch-model.git
cd lib
ln -s ../p5-elasticsearch-model/lib/ElasticSearchX .
```

Not the most elegant way to do things, but it works and it'll be available when you run ./bin/prove without requiring any additional flags.  Make sure you do a `carton install` or `vagrant provision` after pulling in the changes.

In order to run this on your VM:

```
cd metacpan-puppet
git fetch
git co -b oalders/elasticsearch-upgrade origin/oalders/elasticsearch-upgrade
vagrant provision
```

To run the tests on your VM you'll (temporarily) need to use the "live" Elasticsearch instance.  Keep in mind that doing this will blow away anything you may have previously indexed.  We're still working on a fix for this.

```
vagrant ssh
cd metacpan-api
METACPAN_ES_TEST_PORT=9200 ./bin/prove
```

### CODE REVIEW

**Comment by andreeap** [comment]
I was on the wrong repository and merged by accident this into the master, but I reverted the merge.

**Comment by oalders** [comment]
I've fixed it now.  Don't click any more merge buttons or push to master.  :)  You'll  need to delete your master and grab the current version as your history is out of sync.

**Comment by andreeap** [comment]
Thank you, I was extremely scared for what I have done.

**Comment by oalders** [comment]
This has mostly been moved to #405

**Pull request closed without merging**
