### PR TITLE
[WIP] Elasticsearch 2.x

### PR DESCRIPTION
**Pull request by oalders**
This is the branch which we will merge into production at QAH.

### CODE REVIEW

**Comment by oalders** [comment]
The merge broke a bunch of stuff.  I'm trying to fix it, but I'd hold off on pulling in any changes locally until that happens.

**Comment by oalders** [comment]
I think so!

**Comment by oalders** [comment]
@mickeyn would you like to do the honours?

**Comment by mickeyn** [comment]
sure :)

**Pull request merged**
